// The sound catalog: every sound the room can play, with a fixed category taxonomy (crate strata,
// analyzer priors, prompt grouping), family/tags for the composer, playable ranges for soundfonts,
// measured levels, and the fixed registration order of sample maps.
// Generated by `npm run catalog` (scripts/build-catalog.ts) into palette/catalog.json; sample maps
// are vendored into palette/maps/ with `_base` rewritten to commit-pinned raw.githubusercontent URLs.
// Server (validator known-sounds, analyzer, crate, prompt) and client (registration) read the same
// file, so `s("bd:3")` means the same file for everyone. A small fixture for tests lives in
// test/fixtures/catalog.small.json. Parsing/indexing helpers: src/strudel/catalog.ts.

/** Fixed top-level taxonomy. Crate strata draw by category; families refine within it. */
export const SOUND_CATEGORIES = ['percussion', 'bass', 'harmonic', 'melodic', 'texture', 'vocal'] as const;
export type SoundCategory = (typeof SOUND_CATEGORIES)[number];

export type SoundKind = 'synth' | 'sample' | 'soundfont' | 'wavetable';

export interface CatalogSound {
  /** Registered sound id, lower-case, as superdough resolves it (bank applied), e.g. "rolandtr909_bd". */
  id: string;
  kind: SoundKind;
  category: SoundCategory;
  /**
   * `<category-ish>/<detail>` from a closed list maintained in scripts/build-catalog.ts, e.g.
   * "drum-machine/kick", "drum-machine/hat", "break/loop", "gm/keys", "gm/strings", "vcsl/mallet",
   * "synth/basic", "wavetable/akwf", "field/nature".
   */
  family: string;
  /** Short comma-separated descriptors for the composer, e.g. "warm, acoustic, bowed". */
  tags: string;
  /** Human label for the UI, e.g. "TR-909 kick", "Vibraphone". */
  label: string;
  /** Number of variants (samples in the bank, or soundfont variants selectable with n). */
  count: number;
  /** Pitched sources respond to note(); unpitched ones use n() as a sample index. */
  pitched: boolean;
  /** Map id this came from (see CatalogMap.id); "builtin" for synths. */
  source: string;
  /** Drum machine name for bank sounds, e.g. "RolandTR909". */
  machine?: string;
  /** How to write it in code, e.g. { s: "bd", bank: "RolandTR909" } or { s: "gm_epiano1" }. */
  usage: { s: string; bank?: string };
  /** Playable MIDI range for soundfont variant 0 (notes outside may be silent or hang). */
  range?: [number, number];
  /** Brightness prior 0..1 (spectral centroid, measured when possible, else by family). */
  brightness: number;
  /** Measured at gain 1 (C4 or n=0, 1 s) by the offline renderer; null when not measured. */
  level: { rmsDb: number; peakDb: number; centroidHz: number } | null;
  /** Approximate size and length of variant 0 (memory budgeting; long pads excluded from crates). */
  bytes?: number;
  durationSec?: number;
  /** Aliases that resolve to the same sound (e.g. short drum-machine bank aliases). */
  aliases?: string[];
  license: string;
}

export interface CatalogMap {
  id: string;
  /** "samples" maps go to samples(); "bank-aliases" to aliasBank() after the drum machines. */
  kind: 'samples' | 'bank-aliases';
  /** Vendored map path served by our server, e.g. "/palette/maps/dirt-samples.json". */
  path: string;
  /** Upstream repo + pinned commit, for attribution and reproducibility. */
  upstream: string;
  license: string;
  /** Registration order; the build asserts there are no name collisions across maps. */
  order: number;
}

export interface Catalog {
  version: string;
  generatedAt: string;
  /** Commit-pinned raw.githubusercontent.com base for setSoundfontUrl() (immutable content). */
  soundfontBase: string;
  maps: CatalogMap[];
  sounds: CatalogSound[];
}

/** Where the server serves the catalog; clients fetch it at boot. */
export const CATALOG_URL = '/palette/catalog.json';

/** Sounds that exist but the composer may not use (code-execution sinks or engine internals). */
export const BLOCKED_SOUNDS: ReadonlySet<string> = new Set(['bytebeat', 'bus', 'user', 'one']);
