// The sound catalog: every sound the room can play, with family/tags for the composer's crate,
// playable ranges for soundfonts, and the fixed registration order of sample maps.
// Generated by `npm run catalog` (scripts/build-catalog.ts) into palette/catalog.json; sample maps
// are vendored into palette/maps/ with `_base` rewritten to commit-pinned raw.githubusercontent URLs.
// Server (validator known-sounds, crate, prompt) and client (registration) read the same file, so
// `s("bd:3")` means the same file for everyone.

export type SoundKind = 'synth' | 'sample' | 'soundfont' | 'wavetable';

export interface CatalogSound {
  /** Registered sound id, lower-case, as superdough resolves it (bank applied), e.g. "rolandtr909_bd". */
  id: string;
  kind: SoundKind;
  /** Hierarchical family used for crate stratification, e.g. "drum-machine/kick", "gm/strings", "vcsl/mallet". */
  family: string;
  /** Short comma-separated descriptors for the composer, e.g. "warm, acoustic, bowed". */
  tags: string;
  /** Human label for the UI, e.g. "TR-909 kick", "Vibraphone". */
  label: string;
  /** Number of variants (samples in the bank, or soundfont variants selectable with n). */
  count: number;
  /** Pitched sources respond to note(); unpitched ones to n() as sample index. */
  pitched: boolean;
  /** Map id this came from (see CatalogMap.id). */
  source: string;
  /** For drum machines: how to write it — s("bd").bank("RolandTR909"). */
  usage?: { s: string; bank?: string };
  /** Playable MIDI range for soundfont variant 0 (notes outside may be silent or hang). */
  range?: [number, number];
  /** Aliases that resolve to the same sound (e.g. short drum-machine bank aliases). */
  aliases?: string[];
  license?: string;
}

export interface CatalogMap {
  id: string;
  /** Vendored map path served by our server, e.g. "/palette/maps/dirt-samples.json". */
  path: string;
  /** Upstream repo + pinned commit, for attribution and reproducibility. */
  upstream: string;
  license: string;
  /** Registration order; later maps win name collisions (there should be none — the build asserts). */
  order: number;
}

export interface Catalog {
  version: string;
  generatedAt: string;
  /** Pinned soundfont base URL for setSoundfontUrl(). */
  soundfontBase: string;
  maps: CatalogMap[];
  sounds: CatalogSound[];
}

/** Sounds that exist but the composer may not use (code-execution sinks or engine internals). */
export const BLOCKED_SOUNDS: ReadonlySet<string> = new Set(['bytebeat', 'bus', 'user', 'one']);
