// The sound catalog: every sound the room can play, with a fixed category taxonomy (crate strata,
// analyzer priors, prompt grouping), family/tags for the composer, playable ranges for soundfonts,
// measured levels, and the fixed registration order of sample maps.
// Generated by `npm run catalog` (scripts/build-catalog.ts) into palette/catalog.json; sample maps
// are vendored into palette/maps/ with `_base` rewritten to commit-pinned raw.githubusercontent URLs.
// Server (validator known-sounds, analyzer, crate, prompt) and client (registration) read the same
// file, so `s("bd:3")` means the same file for everyone. A small fixture for tests lives in
// test/fixtures/catalog.small.json. Parsing/indexing helpers: src/strudel/catalog.ts.

/** Fixed top-level taxonomy. Crate strata draw by category; families refine within it. */
export const SOUND_CATEGORIES = ['percussion', 'bass', 'harmonic', 'melodic', 'texture', 'vocal'] as const;
export type SoundCategory = (typeof SOUND_CATEGORIES)[number];

export type SoundKind = 'synth' | 'sample' | 'soundfont' | 'wavetable';

export interface CatalogSound {
  /** Registered sound id, lower-case, as superdough resolves it (bank applied), e.g. "rolandtr909_bd". */
  id: string;
  kind: SoundKind;
  category: SoundCategory;
  /**
   * `<category-ish>/<detail>` from a closed list maintained in scripts/build-catalog.ts, e.g.
   * "drum-machine/kick", "drum-machine/hat", "break/loop", "gm/keys", "gm/strings", "vcsl/mallet",
   * "synth/basic", "wavetable/akwf", "field/nature".
   */
  family: string;
  /** Short comma-separated descriptors for the composer, e.g. "warm, acoustic, bowed". */
  tags: string;
  /** Human label for the UI, e.g. "TR-909 kick", "Vibraphone". */
  label: string;
  /** Number of variants (samples in the bank, or soundfont variants selectable with n). */
  count: number;
  /**
   * Variant indices (0…count-1) that don't exist upstream and play silence, e.g. [11] for
   * gm_gunshot. `n` selects variant round(n) mod count, so n = 23 fails there too. Absent when all play.
   */
  failingVariants?: number[];
  /** Pitched sources respond to note(); unpitched ones use n() as a sample index. */
  pitched: boolean;
  /** Map id this came from (see CatalogMap.id); "builtin" for synths. */
  source: string;
  /** Drum machine name for bank sounds, e.g. "RolandTR909". */
  machine?: string;
  /** How to write it in code, e.g. { s: "bd", bank: "RolandTR909" } or { s: "gm_epiano1" }. */
  usage: { s: string; bank?: string };
  /** Playable MIDI range for soundfont variant 0 (notes outside may be silent or hang). */
  range?: [number, number];
  /** Brightness prior 0..1 (spectral centroid, measured when possible, else by family). */
  brightness: number;
  /**
   * One event rendered offline (scripts/render-audio.ts) at gain 1 and n=0, pitched sounds at C4
   * (a soundfont that can't play C4 at the middle of its range), held for 1 s; sample files
   * (`kind: 'sample'`) are clipped to the event (clip: 1). null when not measured or silent.
   * - `rmsDb`: RMS in dBFS of both channels over the 1 s from onset, i.e. energy per event: a
   *   one-shot reads low (its energy is spread over the second), a sustained sound reads its
   *   steady-state level.
   * - `peakDb`: the sample peak of either channel (no oversampling).
   * - `centroidHz`: spectral centroid of the mid channel, magnitude-weighted within each 2048-point
   *   frame and averaged over frames weighted by their energy (frames 60 dB below the loudest skipped).
   * A part's RMS from these: roughly rmsDb + 10·log10(onsets per second) for hits that don't overlap
   * (for a sustained sound, + 10·log10(the fraction of time it sounds) instead), then
   * + 20·log10(gain × velocity): −1.9 dB at superdough's default gain of 0.8.
   */
  level: { rmsDb: number; peakDb: number; centroidHz: number } | null;
  /** Approximate size and length of variant 0 (memory budgeting; long pads excluded from crates). */
  bytes?: number;
  durationSec?: number;
  /** Aliases that resolve to the same sound (e.g. short drum-machine bank aliases). */
  aliases?: string[];
  license: string;
}

export interface CatalogMap {
  id: string;
  /** "samples" maps go to samples(); "bank-aliases" to aliasBank() after the drum machines. */
  kind: 'samples' | 'bank-aliases';
  /** Vendored map path served by our server, e.g. "/palette/maps/dirt-samples.json". */
  path: string;
  /** Upstream repo + pinned commit, for attribution and reproducibility. */
  upstream: string;
  license: string;
  /** Registration order; the build asserts there are no name collisions across maps. */
  order: number;
}

export interface Catalog {
  version: string;
  generatedAt: string;
  /** Commit-pinned raw.githubusercontent.com base for setSoundfontUrl() (immutable content). */
  soundfontBase: string;
  maps: CatalogMap[];
  sounds: CatalogSound[];
}

/** Where the server serves the catalog; clients fetch it at boot. */
export const CATALOG_URL = '/palette/catalog.json';

/** Sounds that exist but the composer may not use (code-execution sinks or engine internals). */
export const BLOCKED_SOUNDS: ReadonlySet<string> = new Set(['bytebeat', 'bus', 'user', 'one']);

/** The variant superdough plays for `n`: round(n) mod count, non-numbers as 0 (superdough util.mjs getSoundIndex). */
export function variantIndex(n: unknown, count: number): number {
  const x = Number(n);
  const i = Math.round(Number.isNaN(x) ? 0 : x);
  return ((i % count) + count) % count;
}

/** The variant `n` selects on `sound` when that variant plays silence (CatalogSound.failingVariants), else null. */
export function failingVariant(sound: CatalogSound, n: unknown): number | null {
  if (!sound.failingVariants?.length || sound.count < 1) return null;
  const variant = variantIndex(n, sound.count);
  return sound.failingVariants.includes(variant) ? variant : null;
}
